### ISSUE TITLE
year and month are not changed, when date is selected from different year( after deselecting the previous date )

### ISSUE THREAD

**Issue by merakhi** [qodesmith/datepicker#52] opened 2019-04-16 13:06 UTC
In the below image i have selected 1st dec 2018 date
<img width="237" alt="todate-inital" src="https://user-images.githubusercontent.com/27452811/56211466-993f1880-6075-11e9-90b1-db478331fcf0.PNG">

then i de-selected it
<img width="296" alt="to-date2 deselect" src="https://user-images.githubusercontent.com/27452811/56211507-acea7f00-6075-11e9-9cc1-da8a334aa31e.PNG">

and again when i select 5 april 2019
it is changing only day not month and year

<img width="271" alt="to-date again selected" src="https://user-images.githubusercontent.com/27452811/56211596-d5727900-6075-11e9-820d-1adb2fe8ad2c.PNG">

please look into this issue

**Comment by qodesmith** [comment] 2019-05-19 13:19
Thanks for your patience. Just settled down in a new job so I'll be spending some time on resolving bugs.

**Comment by qodesmith** [comment] 2019-06-18 23:24
@merakhi Try downloading the latest version. I'm unable to reproduce this.

**Comment by qodesmith** [comment] 2019-06-22 15:47
Let me know if this is still an issue and I'll reopen this. Closing for now.

**Closed by qodesmith** 2019-06-22 15:47 UTC
